variable "vsphere_user" {}
variable "vsphere_password" {}
variable "vsphere_server" {}
variable "vsphere_allow_unverified_ssl" {}
variable "vsphere_dc" {}
variable "vsphere_datastore" {}
variable "vsphere_pool" {}
variable "vsphere_network" {}
variable "vsphere_template_name" {}
#variable "vsphere_datastore_cluster" {}

variable "compute_instance_count" {}
variable "compute_name_prefix" {}
variable "compute_cpus" {}
variable "compute_mem" {}
variable "compute_guest_id" {}
variable "compute_disk_label" {}
variable "compute_disk_size" {}
variable "compute_instance_folder" {}
